# Generated by Django 2.2.12 on 2021-03-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentHighlight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('sentence', models.CharField(max_length=5000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WordStreak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
